### PR TITLE
Added prop to set what events to emit

### PR DESCRIPTION
**Pull request by gismya**
Instead of registering all the possible events as event listeners, I wanted a prop to choose what events to register and emit. Should not mess with any existing implementation since the prop has the same default value as before.

### CODE REVIEW

**Comment by dobromir-hristov** [comment]
What was the issue, aome events were not getting fired? Or too much noise?

**Comment by gismya** [comment]
Too much noise, and a potential (but rather improbable) performance hit.
Totally understand if it is not a change you want to make in the repo, but
since I made it for the project I'm working on I figured I'd share and see
if it was of more general use.

**Comment by dobromir-hristov** [comment]
It's fine, I don't see a problem with it. Please document the prop and revert the two dist files

**Comment by gismya** [comment]
Thank you for the by far fastest PR process I've experienced in an open source project :)

**Comment by dobromir-hristov** [comment]
I will release a bit later

**Pull request merged**
